//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.11.18 at 10:56:47 AM IST 
//


package com.codea2z.xmlobject;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ShipmentRequest }
     * 
     */
    public ShipmentRequest createShipmentRequest() {
        return new ShipmentRequest();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Buyer }
     * 
     */
    public ShipmentRequest.Buyer createShipmentRequestBuyer() {
        return new ShipmentRequest.Buyer();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Buyer.RegistrationNumbers }
     * 
     */
    public ShipmentRequest.Buyer.RegistrationNumbers createShipmentRequestBuyerRegistrationNumbers() {
        return new ShipmentRequest.Buyer.RegistrationNumbers();
    }

    /**
     * Create an instance of {@link ShipmentRequest.UltimateConsignee }
     * 
     */
    public ShipmentRequest.UltimateConsignee createShipmentRequestUltimateConsignee() {
        return new ShipmentRequest.UltimateConsignee();
    }

    /**
     * Create an instance of {@link ShipmentRequest.UltimateConsignee.RegistrationNumbers }
     * 
     */
    public ShipmentRequest.UltimateConsignee.RegistrationNumbers createShipmentRequestUltimateConsigneeRegistrationNumbers() {
        return new ShipmentRequest.UltimateConsignee.RegistrationNumbers();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Payer }
     * 
     */
    public ShipmentRequest.Payer createShipmentRequestPayer() {
        return new ShipmentRequest.Payer();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Payer.RegistrationNumbers }
     * 
     */
    public ShipmentRequest.Payer.RegistrationNumbers createShipmentRequestPayerRegistrationNumbers() {
        return new ShipmentRequest.Payer.RegistrationNumbers();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Seller }
     * 
     */
    public ShipmentRequest.Seller createShipmentRequestSeller() {
        return new ShipmentRequest.Seller();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Seller.RegistrationNumbers }
     * 
     */
    public ShipmentRequest.Seller.RegistrationNumbers createShipmentRequestSellerRegistrationNumbers() {
        return new ShipmentRequest.Seller.RegistrationNumbers();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Exporter }
     * 
     */
    public ShipmentRequest.Exporter createShipmentRequestExporter() {
        return new ShipmentRequest.Exporter();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Exporter.RegistrationNumbers }
     * 
     */
    public ShipmentRequest.Exporter.RegistrationNumbers createShipmentRequestExporterRegistrationNumbers() {
        return new ShipmentRequest.Exporter.RegistrationNumbers();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Importer }
     * 
     */
    public ShipmentRequest.Importer createShipmentRequestImporter() {
        return new ShipmentRequest.Importer();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Importer.RegistrationNumbers }
     * 
     */
    public ShipmentRequest.Importer.RegistrationNumbers createShipmentRequestImporterRegistrationNumbers() {
        return new ShipmentRequest.Importer.RegistrationNumbers();
    }

    /**
     * Create an instance of {@link ShipmentRequest.DGs }
     * 
     */
    public ShipmentRequest.DGs createShipmentRequestDGs() {
        return new ShipmentRequest.DGs();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Label }
     * 
     */
    public ShipmentRequest.Label createShipmentRequestLabel() {
        return new ShipmentRequest.Label();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Shipper }
     * 
     */
    public ShipmentRequest.Shipper createShipmentRequestShipper() {
        return new ShipmentRequest.Shipper();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Shipper.RegistrationNumbers }
     * 
     */
    public ShipmentRequest.Shipper.RegistrationNumbers createShipmentRequestShipperRegistrationNumbers() {
        return new ShipmentRequest.Shipper.RegistrationNumbers();
    }

    /**
     * Create an instance of {@link ShipmentRequest.ShipmentDetails }
     * 
     */
    public ShipmentRequest.ShipmentDetails createShipmentRequestShipmentDetails() {
        return new ShipmentRequest.ShipmentDetails();
    }

    /**
     * Create an instance of {@link ShipmentRequest.ShipmentDetails.Pieces }
     * 
     */
    public ShipmentRequest.ShipmentDetails.Pieces createShipmentRequestShipmentDetailsPieces() {
        return new ShipmentRequest.ShipmentDetails.Pieces();
    }

    /**
     * Create an instance of {@link ShipmentRequest.ShipmentDetails.Pieces.Piece }
     * 
     */
    public ShipmentRequest.ShipmentDetails.Pieces.Piece createShipmentRequestShipmentDetailsPiecesPiece() {
        return new ShipmentRequest.ShipmentDetails.Pieces.Piece();
    }

    /**
     * Create an instance of {@link ShipmentRequest.ShipmentDetails.Pieces.Piece.AdditionalInformation }
     * 
     */
    public ShipmentRequest.ShipmentDetails.Pieces.Piece.AdditionalInformation createShipmentRequestShipmentDetailsPiecesPieceAdditionalInformation() {
        return new ShipmentRequest.ShipmentDetails.Pieces.Piece.AdditionalInformation();
    }

    /**
     * Create an instance of {@link ShipmentRequest.ExportDeclaration }
     * 
     */
    public ShipmentRequest.ExportDeclaration createShipmentRequestExportDeclaration() {
        return new ShipmentRequest.ExportDeclaration();
    }

    /**
     * Create an instance of {@link ShipmentRequest.ExportDeclaration.InvoiceReferences }
     * 
     */
    public ShipmentRequest.ExportDeclaration.InvoiceReferences createShipmentRequestExportDeclarationInvoiceReferences() {
        return new ShipmentRequest.ExportDeclaration.InvoiceReferences();
    }

    /**
     * Create an instance of {@link ShipmentRequest.ExportDeclaration.CustomsDocuments }
     * 
     */
    public ShipmentRequest.ExportDeclaration.CustomsDocuments createShipmentRequestExportDeclarationCustomsDocuments() {
        return new ShipmentRequest.ExportDeclaration.CustomsDocuments();
    }

    /**
     * Create an instance of {@link ShipmentRequest.ExportDeclaration.ExportLineItem }
     * 
     */
    public ShipmentRequest.ExportDeclaration.ExportLineItem createShipmentRequestExportDeclarationExportLineItem() {
        return new ShipmentRequest.ExportDeclaration.ExportLineItem();
    }

    /**
     * Create an instance of {@link ShipmentRequest.ExportDeclaration.ExportLineItem.CustomsPaperworks }
     * 
     */
    public ShipmentRequest.ExportDeclaration.ExportLineItem.CustomsPaperworks createShipmentRequestExportDeclarationExportLineItemCustomsPaperworks() {
        return new ShipmentRequest.ExportDeclaration.ExportLineItem.CustomsPaperworks();
    }

    /**
     * Create an instance of {@link ShipmentRequest.ExportDeclaration.ExportLineItem.ItemReferences }
     * 
     */
    public ShipmentRequest.ExportDeclaration.ExportLineItem.ItemReferences createShipmentRequestExportDeclarationExportLineItemItemReferences() {
        return new ShipmentRequest.ExportDeclaration.ExportLineItem.ItemReferences();
    }

    /**
     * Create an instance of {@link ShipmentRequest.ExportDeclaration.OtherCharges }
     * 
     */
    public ShipmentRequest.ExportDeclaration.OtherCharges createShipmentRequestExportDeclarationOtherCharges() {
        return new ShipmentRequest.ExportDeclaration.OtherCharges();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Consignee }
     * 
     */
    public ShipmentRequest.Consignee createShipmentRequestConsignee() {
        return new ShipmentRequest.Consignee();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Consignee.RegistrationNumbers }
     * 
     */
    public ShipmentRequest.Consignee.RegistrationNumbers createShipmentRequestConsigneeRegistrationNumbers() {
        return new ShipmentRequest.Consignee.RegistrationNumbers();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Request }
     * 
     */
    public ShipmentRequest.Request createShipmentRequestRequest() {
        return new ShipmentRequest.Request();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Billing }
     * 
     */
    public ShipmentRequest.Billing createShipmentRequestBilling() {
        return new ShipmentRequest.Billing();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Dutiable }
     * 
     */
    public ShipmentRequest.Dutiable createShipmentRequestDutiable() {
        return new ShipmentRequest.Dutiable();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Reference }
     * 
     */
    public ShipmentRequest.Reference createShipmentRequestReference() {
        return new ShipmentRequest.Reference();
    }

    /**
     * Create an instance of {@link ShipmentRequest.SpecialService }
     * 
     */
    public ShipmentRequest.SpecialService createShipmentRequestSpecialService() {
        return new ShipmentRequest.SpecialService();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Buyer.Contact }
     * 
     */
    public ShipmentRequest.Buyer.Contact createShipmentRequestBuyerContact() {
        return new ShipmentRequest.Buyer.Contact();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Buyer.RegistrationNumbers.RegistrationNumber }
     * 
     */
    public ShipmentRequest.Buyer.RegistrationNumbers.RegistrationNumber createShipmentRequestBuyerRegistrationNumbersRegistrationNumber() {
        return new ShipmentRequest.Buyer.RegistrationNumbers.RegistrationNumber();
    }

    /**
     * Create an instance of {@link ShipmentRequest.UltimateConsignee.Contact }
     * 
     */
    public ShipmentRequest.UltimateConsignee.Contact createShipmentRequestUltimateConsigneeContact() {
        return new ShipmentRequest.UltimateConsignee.Contact();
    }

    /**
     * Create an instance of {@link ShipmentRequest.UltimateConsignee.RegistrationNumbers.RegistrationNumber }
     * 
     */
    public ShipmentRequest.UltimateConsignee.RegistrationNumbers.RegistrationNumber createShipmentRequestUltimateConsigneeRegistrationNumbersRegistrationNumber() {
        return new ShipmentRequest.UltimateConsignee.RegistrationNumbers.RegistrationNumber();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Payer.Contact }
     * 
     */
    public ShipmentRequest.Payer.Contact createShipmentRequestPayerContact() {
        return new ShipmentRequest.Payer.Contact();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Payer.RegistrationNumbers.RegistrationNumber }
     * 
     */
    public ShipmentRequest.Payer.RegistrationNumbers.RegistrationNumber createShipmentRequestPayerRegistrationNumbersRegistrationNumber() {
        return new ShipmentRequest.Payer.RegistrationNumbers.RegistrationNumber();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Seller.Contact }
     * 
     */
    public ShipmentRequest.Seller.Contact createShipmentRequestSellerContact() {
        return new ShipmentRequest.Seller.Contact();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Seller.RegistrationNumbers.RegistrationNumber }
     * 
     */
    public ShipmentRequest.Seller.RegistrationNumbers.RegistrationNumber createShipmentRequestSellerRegistrationNumbersRegistrationNumber() {
        return new ShipmentRequest.Seller.RegistrationNumbers.RegistrationNumber();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Exporter.Contact }
     * 
     */
    public ShipmentRequest.Exporter.Contact createShipmentRequestExporterContact() {
        return new ShipmentRequest.Exporter.Contact();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Exporter.RegistrationNumbers.RegistrationNumber }
     * 
     */
    public ShipmentRequest.Exporter.RegistrationNumbers.RegistrationNumber createShipmentRequestExporterRegistrationNumbersRegistrationNumber() {
        return new ShipmentRequest.Exporter.RegistrationNumbers.RegistrationNumber();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Importer.Contact }
     * 
     */
    public ShipmentRequest.Importer.Contact createShipmentRequestImporterContact() {
        return new ShipmentRequest.Importer.Contact();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Importer.RegistrationNumbers.RegistrationNumber }
     * 
     */
    public ShipmentRequest.Importer.RegistrationNumbers.RegistrationNumber createShipmentRequestImporterRegistrationNumbersRegistrationNumber() {
        return new ShipmentRequest.Importer.RegistrationNumbers.RegistrationNumber();
    }

    /**
     * Create an instance of {@link ShipmentRequest.DGs.DG }
     * 
     */
    public ShipmentRequest.DGs.DG createShipmentRequestDGsDG() {
        return new ShipmentRequest.DGs.DG();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Label.CustomerLogo }
     * 
     */
    public ShipmentRequest.Label.CustomerLogo createShipmentRequestLabelCustomerLogo() {
        return new ShipmentRequest.Label.CustomerLogo();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Shipper.Contact }
     * 
     */
    public ShipmentRequest.Shipper.Contact createShipmentRequestShipperContact() {
        return new ShipmentRequest.Shipper.Contact();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Shipper.RegistrationNumbers.RegistrationNumber }
     * 
     */
    public ShipmentRequest.Shipper.RegistrationNumbers.RegistrationNumber createShipmentRequestShipperRegistrationNumbersRegistrationNumber() {
        return new ShipmentRequest.Shipper.RegistrationNumbers.RegistrationNumber();
    }

    /**
     * Create an instance of {@link ShipmentRequest.ShipmentDetails.Pieces.Piece.PieceReference }
     * 
     */
    public ShipmentRequest.ShipmentDetails.Pieces.Piece.PieceReference createShipmentRequestShipmentDetailsPiecesPiecePieceReference() {
        return new ShipmentRequest.ShipmentDetails.Pieces.Piece.PieceReference();
    }

    /**
     * Create an instance of {@link ShipmentRequest.ShipmentDetails.Pieces.Piece.AdditionalInformation.CustomerBarcodes }
     * 
     */
    public ShipmentRequest.ShipmentDetails.Pieces.Piece.AdditionalInformation.CustomerBarcodes createShipmentRequestShipmentDetailsPiecesPieceAdditionalInformationCustomerBarcodes() {
        return new ShipmentRequest.ShipmentDetails.Pieces.Piece.AdditionalInformation.CustomerBarcodes();
    }

    /**
     * Create an instance of {@link ShipmentRequest.ShipmentDetails.Pieces.Piece.AdditionalInformation.CustomerAdditionalInformation }
     * 
     */
    public ShipmentRequest.ShipmentDetails.Pieces.Piece.AdditionalInformation.CustomerAdditionalInformation createShipmentRequestShipmentDetailsPiecesPieceAdditionalInformationCustomerAdditionalInformation() {
        return new ShipmentRequest.ShipmentDetails.Pieces.Piece.AdditionalInformation.CustomerAdditionalInformation();
    }

    /**
     * Create an instance of {@link ShipmentRequest.ExportDeclaration.InvoiceIndicativeCustomsValues }
     * 
     */
    public ShipmentRequest.ExportDeclaration.InvoiceIndicativeCustomsValues createShipmentRequestExportDeclarationInvoiceIndicativeCustomsValues() {
        return new ShipmentRequest.ExportDeclaration.InvoiceIndicativeCustomsValues();
    }

    /**
     * Create an instance of {@link ShipmentRequest.ExportDeclaration.InvoiceReferences.InvoiceReference }
     * 
     */
    public ShipmentRequest.ExportDeclaration.InvoiceReferences.InvoiceReference createShipmentRequestExportDeclarationInvoiceReferencesInvoiceReference() {
        return new ShipmentRequest.ExportDeclaration.InvoiceReferences.InvoiceReference();
    }

    /**
     * Create an instance of {@link ShipmentRequest.ExportDeclaration.CustomsDocuments.CustomsDocument }
     * 
     */
    public ShipmentRequest.ExportDeclaration.CustomsDocuments.CustomsDocument createShipmentRequestExportDeclarationCustomsDocumentsCustomsDocument() {
        return new ShipmentRequest.ExportDeclaration.CustomsDocuments.CustomsDocument();
    }

    /**
     * Create an instance of {@link ShipmentRequest.ExportDeclaration.ExportLineItem.Weight }
     * 
     */
    public ShipmentRequest.ExportDeclaration.ExportLineItem.Weight createShipmentRequestExportDeclarationExportLineItemWeight() {
        return new ShipmentRequest.ExportDeclaration.ExportLineItem.Weight();
    }

    /**
     * Create an instance of {@link ShipmentRequest.ExportDeclaration.ExportLineItem.GrossWeight }
     * 
     */
    public ShipmentRequest.ExportDeclaration.ExportLineItem.GrossWeight createShipmentRequestExportDeclarationExportLineItemGrossWeight() {
        return new ShipmentRequest.ExportDeclaration.ExportLineItem.GrossWeight();
    }

    /**
     * Create an instance of {@link ShipmentRequest.ExportDeclaration.ExportLineItem.CustomsPaperworks.CustomsPaperwork }
     * 
     */
    public ShipmentRequest.ExportDeclaration.ExportLineItem.CustomsPaperworks.CustomsPaperwork createShipmentRequestExportDeclarationExportLineItemCustomsPaperworksCustomsPaperwork() {
        return new ShipmentRequest.ExportDeclaration.ExportLineItem.CustomsPaperworks.CustomsPaperwork();
    }

    /**
     * Create an instance of {@link ShipmentRequest.ExportDeclaration.ExportLineItem.ItemReferences.ItemReference }
     * 
     */
    public ShipmentRequest.ExportDeclaration.ExportLineItem.ItemReferences.ItemReference createShipmentRequestExportDeclarationExportLineItemItemReferencesItemReference() {
        return new ShipmentRequest.ExportDeclaration.ExportLineItem.ItemReferences.ItemReference();
    }

    /**
     * Create an instance of {@link ShipmentRequest.ExportDeclaration.OtherCharges.OtherCharge }
     * 
     */
    public ShipmentRequest.ExportDeclaration.OtherCharges.OtherCharge createShipmentRequestExportDeclarationOtherChargesOtherCharge() {
        return new ShipmentRequest.ExportDeclaration.OtherCharges.OtherCharge();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Consignee.Contact }
     * 
     */
    public ShipmentRequest.Consignee.Contact createShipmentRequestConsigneeContact() {
        return new ShipmentRequest.Consignee.Contact();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Consignee.RegistrationNumbers.RegistrationNumber }
     * 
     */
    public ShipmentRequest.Consignee.RegistrationNumbers.RegistrationNumber createShipmentRequestConsigneeRegistrationNumbersRegistrationNumber() {
        return new ShipmentRequest.Consignee.RegistrationNumbers.RegistrationNumber();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Request.ServiceHeader }
     * 
     */
    public ShipmentRequest.Request.ServiceHeader createShipmentRequestRequestServiceHeader() {
        return new ShipmentRequest.Request.ServiceHeader();
    }

    /**
     * Create an instance of {@link ShipmentRequest.Request.MetaData }
     * 
     */
    public ShipmentRequest.Request.MetaData createShipmentRequestRequestMetaData() {
        return new ShipmentRequest.Request.MetaData();
    }

}
